google/built_value.dart

CHANGELOG.md
built_value/pubspec.yaml
built_value_generator/lib/built_value_generator.dart
built_value_generator/pubspec.yaml
built_value_generator/test/built_value_generator_test.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/28)

Improve error output on failure to generate.

---

CHANGELOG.md
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/35)

Upgrade analyzer, build and source_gen dependencies. Release 0.1.4.

---

CHANGELOG.md
built_value_generator/lib/src/source_class.dart
built_value_generator/lib/src/source_class.g.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/43)

Add checking for correct type arguments for Built and Builder interfaces.

---

CHANGELOG.md
built_value_generator/lib/src/source_class.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/45)

Generate empty constructor with semicolon instead of {}.

---

CHANGELOG.md
built_value/pubspec.yaml
built_value_generator/lib/src/source_class.dart
built_value_generator/lib/src/source_class.g.dart
built_value_generator/lib/src/source_field.g.dart
built_value_generator/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/47)

Use ArgumentError.notNull for null errors.

---

CHANGELOG.md
built_value_generator/lib/src/source_field.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/48)

Reject dynamic fields.

---

CHANGELOG.md
built_value_generator/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/50)

Update pubspec for 0.1.6 release.

---

built_value_generator/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/52)

Release 0.2.0.

---

CHANGELOG.md
built_value/pubspec.yaml
built_value_generator/lib/src/built_parameters_visitor.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/pubspec.yaml
built_value_generator/test/built_value_generator_test.dart
example/pubspec.yaml

Fixes #53 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/55)

Fix generation when class extends multiple interfaces.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/built_list_multimap_serializer.dart
built_value/lib/src/built_set_multimap_serializer.dart
built_value/test/built_list_multimap_serializer_test.dart
built_value/test/built_set_multimap_serializer_test.dart
built_value_generator/lib/src/serializer_source_field.dart
example/lib/serializers.g.dart
example/test/collections_serializer_test.dart

And uncomment the serialization test for collections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/59)

Add serialization of BuiltListMultimap and BuiltSetMultimap.

---

built_value_generator/lib/built_value_generator.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/62)

Remove unnecessary library statements.

---

built_value/lib/src/built_set_multimap_serializer.dart
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
example/pubspec.yaml
example/test/has_int_serializer_test.dart
example/test/simple_value_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/63)

Release 0.3.0.

---

chat_example/pubspec.yaml
example/pubspec.yaml

Fixes #68
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/69)

Fix pubspecs.

---

benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/lib/data_model/data_model.g.dart
chat_example/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/73)

Release 0.4.0.

---

CHANGELOG.md
benchmark/lib/benchmark.dart
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_field.dart
built_value_generator/lib/src/enum_source_library.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/pubspec.yaml
built_value_generator/test/serializer_generator_test.dart
chat_example/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/74)

Fix analyzer issues and generator crash.

---

benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
example/pubspec.yaml
tool/set_version
tool/use_local_deps

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/75)

Release 0.4.1. Add scripts to help.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/78)

Release 0.4.2.

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/79)

Add an articles section to the README

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/82)

Release 0.4.3.

---

chat_example/README.md
chat_example/lib/server/http_server_connection.dart
chat_example/lib/server/resource_server.dart
chat_example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/84)

Serve with proxy

---

chat_example/lib/client/client.dart
chat_example/lib/client/html_display.dart
chat_example/lib/testing/fake_display.dart
chat_example/lib/testing/test_user.dart
chat_example/test/chat_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/90)

Minor fixes to chat example.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/built_value.dart
built_value_generator/lib/src/memoized_getter.dart
built_value_generator/lib/src/memoized_getter.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
example/lib/memoization.dart
example/lib/memoization.g.dart
example/pubspec.yaml
example/test/memoization_test.dart

Fixes https://github.com/google/built_value.dart/issues/38
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/86)

Add @memoize annotation for getters.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value/lib/standard_json_plugin.dart
built_value/test/standard_json_plugin_test.dart
example/test/compound_value_serializer_test.dart

Fixes #65
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/89)

Add StandardJsonPlugin.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
example/lib/serializers.g.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/103)

Release 0.5.1.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/pubspec.yaml
built_value_generator/test/built_value_generator_test.dart
chat_example/pubspec.yaml
end_to_end_test/lib/serializers.g.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
end_to_end_test/test/values_serializer_test.dart
end_to_end_test/test/values_test.dart
example/pubspec.yaml

Fixes #99 
I noticed I dropped some serializer test in the previous commit -- added them back. (SimpleValue, CompoundValue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/106)

Support "import ... as" for field types.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/107)

Release 0.5.2.

---

CHANGELOG.md
benchmark/lib/node.g.dart
benchmark/lib/simple_value.g.dart
benchmark/pubspec.yaml
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/lib/src/enum_source_field.g.dart
built_value_generator/lib/src/enum_source_library.g.dart
built_value_generator/lib/src/memoized_getter.g.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/serializer_source_library.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/pubspec.yaml
chat_example/lib/data_model/data_model.g.dart
chat_example/pubspec.yaml
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/interfaces.g.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
end_to_end_test/test/values_test.dart
example/lib/collections.g.dart
example/lib/generics.g.dart
example/lib/interfaces.g.dart
example/lib/values.g.dart
example/pubspec.yaml

Fixes #33 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/109)

Add null check to generated builder "replace" methods.

---

CHANGELOG.md
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/test/enum_class_generator_test.dart

Fixes #57
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/110)

Fail with error on abstract enum classes.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/test/built_value_generator_test.dart
built_value_generator/test/enum_class_generator_test.dart
built_value_generator/test/serializer_generator_test.dart
chat_example/pubspec.yaml
end_to_end_test/lib/generics.g.dart
end_to_end_test/pubspec.yaml
example/lib/generics.g.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/112)

update to the build 0.7.0, build_test 0.4.0, and build_runner 0.2.0

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/113)

update to build_runner 0.3.0

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/built_value_generator.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_library.dart
built_value_generator/pubspec.yaml
built_value_generator/test/serializer_generator_test.dart
chat_example/lib/data_model/data_model.dart
chat_example/pubspec.yaml
end_to_end_test/lib/collections.dart
end_to_end_test/lib/enums.dart
end_to_end_test/lib/generics.dart
end_to_end_test/lib/interfaces.dart
end_to_end_test/lib/values.dart
end_to_end_test/pubspec.yaml
example/lib/collections.dart
example/lib/enums.dart
example/lib/generics.dart
example/lib/interfaces.dart
example/lib/values.dart
example/pubspec.yaml

Fixes #66
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/116)

Add check for serializer declarations.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart

Fixes #67
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/121)

Streamline generation for classes with no fields

---

CHANGELOG.md
benchmark/lib/node.g.dart
benchmark/lib/simple_value.g.dart
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/lib/src/enum_source_field.g.dart
built_value_generator/lib/src/enum_source_library.g.dart
built_value_generator/lib/src/memoized_getter.g.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/serializer_source_library.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/lib/src/value_source_field.g.dart
chat_example/lib/data_model/data_model.g.dart
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/interfaces.g.dart
end_to_end_test/lib/values.g.dart
example/lib/collections.g.dart
example/lib/generics.g.dart
example/lib/interfaces.g.dart
example/lib/values.g.dart

Fixes #87
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/122)

Add identical check to generated operator==.

---

CHANGELOG.md
analysis_options.yaml
benchmark/lib/node.g.dart
benchmark/lib/simple_value.g.dart
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/lib/src/enum_source_field.g.dart
built_value_generator/lib/src/enum_source_library.g.dart
built_value_generator/lib/src/memoized_getter.g.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/serializer_source_library.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/test/enum_class_generator_test.dart
chat_example/lib/data_model/data_model.g.dart
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/enums.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/interfaces.g.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/generics_test.dart
example/lib/collections.g.dart
example/lib/enums.g.dart
example/lib/generics.g.dart
example/lib/interfaces.g.dart
example/lib/values.g.dart

Fixes #118 
Fixes #64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/123)

Fix for implicit-dynamic:false and implicit-cast:false.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/127)

Release 0.5.4.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_field.dart
end_to_end_test/lib/generics.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/test/generics_serializer_test.dart

Fixes #125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/137)

Fix generation when there are nested multi-parameter generics.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_class.dart
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/values.g.dart
example/lib/collections.g.dart
example/lib/values.g.dart

Fixes #130
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/138)

Use cascades in generated code as suggested by lint.

---

built_value_generator/lib/src/value_source_class.dart
example/lib/example.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/140)

Minor fixes.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/serializer.dart
built_value/lib/src/date_time_serializer.dart
built_value/test/date_time_serializer_test.dart
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
end_to_end_test/test/values_serializer_test.dart
example/pubspec.yaml

Fixes #111 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/143)

Add serializer for "DateTime" fields.

---

CHANGELOG.md
built_value/lib/src/double_serializer.dart
built_value/lib/src/num_serializer.dart
built_value/test/double_serializer_test.dart
built_value/test/num_serializer_test.dart

Note that if people want different strings, they can do that easily using a serializer plugin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/147)

Support serializing NaN, INF and -INF for double and num.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/148)

Release 0.5.6.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/standard_json_plugin.dart
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/serializers.g.dart
end_to_end_test/lib/standard_json.dart
end_to_end_test/lib/standard_json.g.dart
end_to_end_test/pubspec.yaml
end_to_end_test/test/standard_json_serializer_test.dart
example/pubspec.yaml

Fixes #149
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/152)

Ignore nulls when deserializing with StandardJsonPlugin.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/154)

Release 0.5.7.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_library.dart
chat_example/lib/data_model/serializers.g.dart
end_to_end_test/lib/serializers.g.dart
example/lib/serializers.g.dart

Fixes #157
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/161)

Sort serializers in generated output.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/built_value.dart
built_value/lib/json_object.dart
built_value/lib/serializer.dart
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/162)

Release 1.0.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/serializer_source_library.g.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/163)

Allow quiver 0.25.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/LICENSE
built_value_test/lib/matcher.dart
built_value_test/pubspec.yaml
built_value_test/test/matcher_test.dart
built_value_test/test/values.dart
built_value_test/test/values.g.dart
built_value_test/tool/build.dart
chat_example/pubspec.yaml
example/pubspec.yaml
tool/presubmit

Fixes #156
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/164)

Add "built_value_test" library with matcher.

---

benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

In order to work with `angular2` 3.1.0
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/166)

Update dependencies of built_value_generator

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/167)

Release 1.1.1

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/169)

Release 1.1.2

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/serializer_source_library.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/170)

Fix imports, remove dependency on package:meta.

---

CHANGELOG.md
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/test/enum_class_generator_test.dart
chat_example/lib/data_model/data_model.g.dart
end_to_end_test/lib/enums.g.dart
end_to_end_test/lib/interfaces.g.dart
example/lib/enums.g.dart
example/lib/interfaces.g.dart

Fixes #173 
Fixes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/176)

Fix lints/hints in generated enum code

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/180)

Release 1.1.3 with comments generic syntax.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/181)

Release 1.1.4 with non-comment generic syntax.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/src/value_source_field.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
example/lib/generics.g.dart
example/lib/values.g.dart
example/pubspec.yaml
tool/presubmit

Fixes #183
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/184)

Fix relying on a fully generated builder in a manually maintained builder

---

analysis_options.yaml
built_value/lib/src/built_json_serializers.dart
built_value/lib/src/built_list_multimap_serializer.dart
built_value/lib/src/built_set_multimap_serializer.dart
built_value/lib/src/double_serializer.dart
built_value/lib/standard_json_plugin.dart
built_value/test/built_list_serializer_test.dart
built_value/test/built_map_serializer_test.dart
built_value/test/built_set_serializer_test.dart
built_value/test/date_time_serializer_test.dart
built_value/test/standard_json_plugin_test.dart
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/generics.dart
end_to_end_test/test/generics_serializer_test.dart
end_to_end_test/test/generics_test.dart
end_to_end_test/test/to_string_test.dart
end_to_end_test/test/values_test.dart
example/lib/example.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/185)

Fix analyzer warnings.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/187)

Release 1.2.0.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/191)

Release 1.2.1.

---

CHANGELOG.md
benchmark/lib/node.g.dart
benchmark/lib/simple_value.g.dart
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
built_value_test/test/values.g.dart
chat_example/lib/data_model/data_model.g.dart
chat_example/lib/data_model/serializers.g.dart
chat_example/pubspec.yaml
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/enums.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/interfaces.g.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/lib/standard_json.g.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
example/lib/collections.g.dart
example/lib/enums.g.dart
example/lib/generics.g.dart
example/lib/interfaces.g.dart
example/lib/polymorphism.g.dart
example/lib/serializers.g.dart
example/lib/values.g.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/197)

Release 2.0.0.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_field.dart
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/test/polymorphism_test.dart

Fixes #192 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/201)

Fix noninstantiable built_value fields.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
end_to_end_test/test/values_test.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/204)

Release 2.1.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/src/date_time_serializer.dart
built_value/test/date_time_serializer_test.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
end_to_end_test/test/values_serializer_test.dart
example/pubspec.yaml

Fixes #206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/213)

Fix DateTime serialization to include microseconds.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/216)

Release 3.0.0.

---

CHANGELOG.md
analysis_options.yaml
benchmark/pubspec.yaml
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/lib/server/http_server_connection.dart
chat_example/pubspec.yaml
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/pubspec.yaml
example/lib/polymorphism.g.dart
example/pubspec.yaml
tool/presubmit

Fixes #196
Turn off two lints that aren't useful, "close_sinks" and "one_member_abstracts".
Fix an analyzer error in the chat example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/217)

Add dartanalyzer and dartfmt to presubmit. Mark replace method covariant.

---

CHANGELOG.md
benchmark/pubspec.yaml
benchmark/tool/build.dart
benchmark/tool/watch.dart
built_value_generator/pubspec.yaml
built_value_generator/tool/build.dart
built_value_test/pubspec.yaml
built_value_test/tool/build.dart
chat_example/pubspec.yaml
chat_example/tool/build.dart
chat_example/tool/watch.dart
end_to_end_test/pubspec.yaml
end_to_end_test/tool/build.dart
end_to_end_test/tool/watch.dart
example/pubspec.yaml
example/tool/build.dart
example/tool/watch.dart

Fixes #211
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/218)

Upgrade to build 0.10.0, build_runner 0.4.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/219)

Release 4.0.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/src/memoized_getter.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Fixes #220 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/221)

Make generation robust against bad annotations.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/225)

Release 4.1.0.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/serializer_source_field.g.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/228)

Remove an unneeded use of computeNode in generator.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/229)

Release 4.1.1.

---

built_value_generator/lib/src/value_source_field.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/234)

Add fallback for getting field type.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/test/built_value_generator_test.dart

Fixes #93
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/235)

Forbid custom operator== and hashCode, support custom toString().

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/237)

Release 4.2.0.

---

benchmark/pubspec.yaml
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Fixes #236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/241)

Correct import prefix handling.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/242)

Release 4.2.1.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/serializer.dart
built_value/lib/src/int64_serializer.dart
built_value/pubspec.yaml
built_value/test/int64_serializer_test.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
end_to_end_test/test/values_serializer_test.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/247)

Support serializing Int64.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/248)

Release 4.3.0.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/251)

Release 4.3.1.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/src/fields.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/252)

Fix generation when a field is found via two levels of inheritance.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/253)

Release 4.3.2.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/259)

Allow quiver 0.26. Release 4.3.3.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/265)

Release 4.3.4.

---

benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/266)

Use local deps.

---

built_value_generator/lib/built_value_generator.dart

Let me know if you want a CHANGELOG update too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/267)

Allow invoking `const BuiltValueGenerator`.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
end_to_end_test/test/to_string_test.dart
end_to_end_test/test/values_test.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/271)

Release 4.4.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/pubspec.yaml
built_value_generator/test/built_value_generator_test.dart
built_value_generator/test/enum_class_generator_test.dart
built_value_generator/test/serializer_generator_test.dart
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Fixes #273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/274)

Release 4.4.1. Bump build, build_runner and build_test versions.

---

benchmark/tool/watch.dart
chat_example/tool/watch.dart
end_to_end_test/tool/watch.dart
example/tool/watch.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/283)

Fix analyzer issues.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/generics.dart
end_to_end_test/lib/generics.g.dart

Fixes #280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/285)

Fixes for hand coded builders with generics.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_field.dart
built_value_generator/test/built_value_generator_test.dart

Fixes #277
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/286)

Fail with error on public fields.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/uri_serializer.dart
built_value/test/uri_serializer_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_serializer_test.dart

Fixes #261
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/287)

Support serializing Uri.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_library.dart
built_value_generator/lib/src/serializer_source_library.g.dart
end_to_end_test/lib/serializers.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/test/polymorphism_serializer_test.dart

Fixes #260
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/288)

Support multiple Serializers declarations in one file.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_field.dart
built_value_generator/test/built_value_generator_test.dart

Fixes #256
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/289)

Improve error message for field without type.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_library.dart
built_value_generator/lib/src/value_source_field.dart
end_to_end_test/lib/imported_values.dart
end_to_end_test/lib/imported_values.g.dart
end_to_end_test/lib/serializers.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/test/imported_values_serializer_test.dart
end_to_end_test/test/imported_values_test.dart

Fixes #255 
Actually #255 was already fixed; this adds a test for it, and fixes a couple of other bugs caught by the test.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/292)

Fixes for importing with a prefix.

---

built_value_generator/lib/src/serializer_source_class.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/293)

Add comment.

---

CHANGELOG.md
built_value/lib/built_value.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/test/built_value_generator_test.dart
end_to_end_test/lib/serializers.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_serializer_test.dart

For #144 
Doesn't address the whole issue; the same is needed for enums, too.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/294)

Add wireName to BuiltValue and BuiltValueField.

---

CHANGELOG.md
built_value/lib/built_value.dart
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/lib/src/enum_source_field.dart
built_value_generator/lib/src/enum_source_field.g.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/value_source_field.dart
end_to_end_test/lib/enums.dart
end_to_end_test/lib/enums.g.dart
end_to_end_test/lib/serializers.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/test/enums_serializer_test.dart
example/lib/enums.dart
example/lib/enums.g.dart
example/lib/values.dart
example/lib/values.g.dart

Fixes #144
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/295)

Support overriding wireName for enums.

---

CHANGELOG.md
built_value/lib/standard_json_plugin.dart
built_value/test/standard_json_plugin_test.dart
end_to_end_test/test/standard_json_serializer_test.dart
example/lib/example.dart

Fixes #276
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/296)

Support polymorphism in StandardJsonPlugin.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/298)

Release 4.5.0

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/299)

Fix generation when analyzing using summaries.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/302)

Release 4.5.1.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/310)

Allow quiver 0.27; use built_collection 3.0.0; release 4.5.2.

---

built_value/lib/json_object.dart
built_value_generator/lib/src/value_source_class.dart

Fixes #315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/315)

Fix typo; ArgumentError message should not end in a period.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/317)

Release 4.6.0.

---

CHANGELOG.md
built_value_generator/lib/src/built_parameters_visitor.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/329)

Prohibit use of `extends` in `built_value` classes.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/332)

Prohibit importing built_value using 'show' or 'as'.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/321)

Prohibit sdk collections

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/333)

Release 5.0.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/334)

Allow quiver 0.28; release 5.0.1.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/test/built_value_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/335)

Allow `extends` for some restricted cases.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/336)

Release 5.1.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/lib/src/value_source_class.dart
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/340)

Workaround for analyzer issue.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/341)

Release 5.1.1.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/345)

Release 5.1.2.

---

CHANGELOG.md
built_value_generator/lib/src/dart_types.dart
built_value_generator/lib/src/serializer_source_field.dart
chat_example/lib/data_model/data_model.g.dart
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/imported_values.g.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/lib/standard_json.g.dart
end_to_end_test/lib/values.g.dart
example/lib/collections.g.dart
example/lib/generics.g.dart
example/lib/values.g.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/347)

Generate simpler deserialization code for built_collection instances.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/348)

Release 5.1.3.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/lib/src/built_list_multimap_serializer.dart
built_value/lib/src/built_list_serializer.dart
built_value/lib/src/built_set_multimap_serializer.dart
built_value/lib/src/built_set_serializer.dart
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/355)

Type fixes for DDC.

---

tool/set_version
tool/use_local_deps

Fixes #354
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/357)

Update repo management scripts.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/build.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/359)

Fix yaml files.

---

CHANGELOG.md
built_value/lib/src/double_serializer.dart
built_value/lib/src/num_serializer.dart
built_value/lib/standard_json_plugin.dart
built_value/test/double_serializer_test.dart
built_value/test/num_serializer_test.dart
chat_example/lib/client/client.dart
chat_example/lib/server/server.dart
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart
example/lib/polymorphism.dart
example/lib/polymorphism.g.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/372)

Fix polymorphism

---

CHANGELOG.md
built_value/lib/src/double_serializer.dart
built_value/lib/src/num_serializer.dart
built_value/lib/standard_json_plugin.dart
built_value/test/double_serializer_test.dart
built_value/test/num_serializer_test.dart
chat_example/lib/client/client.dart
chat_example/lib/server/server.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/371)

Fix deprecation warnings.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Increase allowed quiver dependency range to >=0.21.0 <0.30.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/369)

Allow quiver 0.30

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/373)

Release 5.2.2.

---

CHANGELOG.md
built_value_generator/lib/builder.dart
example/build.yaml
example/lib/collections.g.dart
example/lib/enums.g.dart
example/lib/generics.g.dart
example/lib/interfaces.g.dart
example/lib/polymorphism.g.dart
example/lib/serializers.g.dart
example/lib/values.g.dart

Fixes #374
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/377)

Add builder option for header.

---

CHANGELOG.md
built_value_generator/lib/src/dart_types.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/test/serializer_generator_test.dart
end_to_end_test/lib/mixins.dart
end_to_end_test/lib/mixins.g.dart
end_to_end_test/lib/mixins_src.dart

Forbid serialization of functions.
Fixes #367
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/378)

Fix generation when a function field is picked up via inheritance from another file.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/big_int_serializer.dart
built_value/test/big_int_serializer_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_serializer_test.dart

Fixes #365 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/379)

Support serializing BigInt.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_library.dart

Fixes #362
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/380)

Fail with a helpful error message if @SerializersFor contains an undefined symbol.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/381)

Release 5.3.0.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/383)

Release 5.4.0.

---

CHANGELOG.md
built_value/lib/standard_json_plugin.dart
end_to_end_test/test/standard_json_serializer_test.dart

Fixes #389
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/391)

Make StandardJsonPlugin serialize to Map<String, Object>.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/392)

Release 5.4.2.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Fixes #388
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/393)

Allow source_gen 0.8.0; release 5.4.3.

---

CHANGELOG.md
analysis_options.yaml
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/lib/src/value_source_class.dart
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Fixes https://github.com/google/built_value.dart/issues/409
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/410)

Move dep on build_config from built_value to built_value_generator

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/411)

Release 5.4.4.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value/test/built_list_serializer_test.dart
built_value/test/built_map_serializer_test.dart
built_value/test/built_set_serializer_test.dart
end_to_end_test/test/generics_serializer_test.dart
end_to_end_test/test/values_serializer_test.dart

Fixes #408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/419)

Improve error message when deserialization fails.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/generics.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/test/generics_test.dart
example/lib/generics.g.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/421)

Move check for dynamic generic type parameters to value class.

---

CHANGELOG.md
built_value/lib/standard_json_plugin.dart
built_value/test/standard_json_plugin_test.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/lib/standard_json.dart
end_to_end_test/lib/standard_json.g.dart
end_to_end_test/test/standard_json_serializer_test.dart

Fixes #330
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/428)

Support serializing BuiltSet with StandardJsonPlugin.

---

CHANGELOG.md
built_value/lib/iso_8601_date_time_serializer.dart
built_value/lib/standard_json_plugin.dart
built_value/test/iso_8601_date_time_serializer_test.dart

Fixes #272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/429)

Add Iso8601DateTimeSerializer.

---

built_value_generator/lib/src/plugin/plugin.dart
built_value_generator/pubspec.yaml

@davidmorgan
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/431)

Supply new pathContext parameter to ContextRoot

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/432)

Release 5.5.1.

---

README.md

Needs $$ to escape $.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/439)

Fix Intellij code template

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/448)

Release 5.5.2.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/459)

Allow quiver 2.0.0.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/461)

Release 5.5.4.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/462)

Update test version.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/463)

Allow SDK 2.0.0.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/467)

Release 6.0.0.

---

CHANGELOG.md
benchmark/lib/node.g.dart
benchmark/lib/simple_value.g.dart
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
built_value_test/test/values.g.dart
chat_example/lib/data_model/data_model.g.dart
chat_example/pubspec.yaml
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/imported_values.g.dart
end_to_end_test/lib/interfaces.g.dart
end_to_end_test/lib/mixins.g.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/lib/standard_json.g.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/pubspec.yaml
end_to_end_test/test/private_value_test.g.dart
example/lib/collections.g.dart
example/lib/generics.g.dart
example/lib/interfaces.g.dart
example/lib/polymorphism.g.dart
example/lib/values.g.dart
example/pubspec.yaml

Fixes #482
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/482)

Allow built_collection 4.0.0.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/493)

Allow `build_runner` 0.10.0.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/lib/generics.g.dart
end_to_end_test/pubspec.yaml
example/pubspec.yaml
tool/set_version

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/500)

Release 6.1.2

---

built_value_test/lib/matcher.dart
built_value_test/test/matcher_test.dart
built_value_test/test/values.dart
built_value_test/test/values.g.dart
end_to_end_test/lib/generics.g.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/501)

Add built_value_test support for remaining built collections.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/503)

- Add `built_value_test` support for remaining built collections.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/polymorphism.dart

Fixes #481
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/509)

Fix to polymorphic base class restrictions.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_class.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_serializer_test.dart

Fixes #504
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/510)

Allow the dollar character in `wireName` settings.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Fixes #518 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/525)

Bump versions of analyzer, analyzer_plugin, build and builder_runner.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/526)

Release 6.1.5.

---

CHANGELOG.md
built_value_generator/lib/built_value_generator.dart
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/lib/src/enum_source_field.dart
built_value_generator/lib/src/enum_source_field.g.dart
built_value_generator/lib/src/enum_source_library.dart
built_value_generator/lib/src/enum_source_library.g.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/serializer_source_class.g.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/serializer_source_field.g.dart
built_value_generator/lib/src/serializer_source_library.dart
built_value_generator/lib/src/serializer_source_library.g.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/lib/src/value_source_class.g.dart
built_value_generator/lib/src/value_source_field.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/530)

Update for analyzer 0.33.3.

---

CHANGELOG.md
built_value_generator/test/built_value_generator_test.dart
built_value_generator/test/enum_class_generator_test.dart
built_value_generator/test/serializer_generator_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/546)

Fix tests following changes to source_gen error output.

---

CHANGELOG.md
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_library.dart
built_value_generator/test/enum_class_generator_test.dart
end_to_end_test/lib/mixins_src.dart

Fixes #546
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/547)

Fix generation when new `mixin` declarations are used.

---

CHANGELOG.md
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/strings.dart
end_to_end_test/lib/enums.dart
end_to_end_test/lib/enums.g.dart

Fixes #533
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/550)

Support dollar signs in enum value names.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart

Fixes #532
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/551)

Add `serializerForType` and `serializerForWireName` to `Serializers`.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/duration_serializer.dart
built_value/test/duration_serializer_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_serializer_test.dart

Fixes #520 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/552)

Add serializer for `Duration` fields.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_field.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart

Fixes #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/554)

Fix nested collections when using a custom builder.

---

CHANGELOG.md
built_value/lib/built_value.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/test/built_value_generator_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_test.dart

Fixes #540
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/553)

Add an option to `@BuiltValue` to generate comparable builders.

---

example/lib/interfaces.dart
example/lib/values.dart
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/567)

Remove deprecated @virtual annotation.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_field.dart
built_value_generator/lib/src/value_source_field.g.dart
built_value_generator/test/built_value_generator_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_test.dart
tool/presubmit

Fixes #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/571)

Allow custom builders to use setter/getter pairs instead of normal fields.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value/test/serializers_test.dart

Fixes #446
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/575)

Make it possible to merge Serializers.

---

CHANGELOG.md
built_value_generator/lib/src/plugin/plugin.dart
built_value_generator/pubspec.yaml

Fixes #548
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/576)

Allow analyzer 0.34.0.

---

AUTHORS
CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/regexp_serializer.dart
built_value/test/regexp_serializer_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_serializer_test.dart

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/577)

Add serializer for `RegExp` fields.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/578)

Release 6.3.0.

---

CHANGELOG.md
built_value/lib/standard_json_plugin.dart
built_value/test/standard_json_plugin_test.dart

Fixes #594
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/595)

Fix a list serialization corner case.

---

benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/596)

Release 6.3.1.

---

AUTHORS
chat_example/bin/main.dart
chat_example/lib/client/client.dart
chat_example/lib/client/html_display.dart
chat_example/lib/client/http_client_connection.dart
chat_example/lib/client/input.dart
chat_example/lib/data_model/data_model.dart
chat_example/lib/data_model/serializers.dart
chat_example/lib/server/http_server_connection.dart
chat_example/lib/server/resource_server.dart
chat_example/lib/server/server.dart
chat_example/lib/testing/fake_client_connection.dart
chat_example/lib/testing/fake_environment.dart
chat_example/lib/testing/fake_server_connection.dart
chat_example/test/chat_test.dart
chat_example/web/main.dart
example/lib/example.dart
example/lib/interfaces.dart
example/lib/serializers.dart
example/lib/values.dart

Reduce verbosity by removing unnecessary "new" and "const" from 
- [_example_](https://github.com/google/built_value.dart/tree/master/example)
- [_chat_example_](https://github.com/google/built_value.dart/tree/master/chat_example)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/610)

Removes unnecessary "new" and "const" from example projects

---

CHANGELOG.md
built_value/lib/built_value.dart
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_test.dart

Add `@BuiltValue(generateBuilderOnSetField: true).`

---

CHANGELOG.md
built_value_generator/pubspec.yaml

Bump version of analyzer.

---

CHANGELOG.md
built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value/test/serializers_test.dart

Add facility to merge `Serializers` instances.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart

Fix polymorphism with more than one level of non-instantiable classes.

---

CHANGELOG.md
built_value/lib/built_value.dart
built_value/pubspec.yaml
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_test.dart

Add defaultCompare and defaultSerialize field options to @BuiltValue.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/lib/src/value_source_class.dart
chat_example/lib/data_model/data_model.g.dart
end_to_end_test/analysis_options.yaml
end_to_end_test/lib/collections.g.dart
end_to_end_test/lib/generics.g.dart
end_to_end_test/lib/imported_values.g.dart
end_to_end_test/lib/mixins.g.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/lib/standard_json.g.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/collections_test.dart
end_to_end_test/test/imported_values_serializer_test.dart
end_to_end_test/test/interfaces_serializer_test.dart
end_to_end_test/test/polymorphism_serializer_test.dart
end_to_end_test/test/standard_json_serializer_test.dart
end_to_end_test/test/values_test.dart
example/lib/collections.g.dart
example/lib/generics.g.dart
example/lib/values.g.dart

Fix generation for implicit-casts and implicit-dynamic.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_analyzer_plugin/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Release 7.0.8.

---

example/pubspec.yaml

Make it very clear this is not meant to be published!

Example: replace version with `publish_to: none`

---

CHANGELOG.md
built_value/lib/built_value.dart
built_value_generator/lib/src/enum_source_field.dart
built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/pubspec.yaml
built_value_generator/test/enum_class_generator_test.dart
end_to_end_test/lib/enums.dart
end_to_end_test/lib/enums.g.dart
end_to_end_test/lib/serializers.dart
end_to_end_test/lib/serializers.g.dart
end_to_end_test/test/enums_serializer_test.dart

Enum const numbers

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart
end_to_end_test/test/values_test.dart

Memoize hashcode

---

built_value_generator/lib/src/serializer_source_class.dart
built_value_generator/lib/src/value_source_class.dart
built_value_generator/test/built_value_generator_test.dart
built_value_generator/test/serializer_generator_test.dart
end_to_end_test/lib/values.dart
end_to_end_test/lib/values.g.dart

closes #835 (I believe)
I just edited on github and haven't tested yet. Will test with a git dep shortly

Make builder factory check `implName`-based

---

built_value/analysis_options.yaml
end_to_end_test/analysis_options.yaml

Remove `non-nullable` experiment from analysis_options

---

built_value/lib/serializer.dart
built_value/lib/src/built_json_serializers.dart
built_value/test/serializers_test.dart

Add serializer toJson/fromJson.

---

built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/lib/polymorphism_nnbd.g.dart

Add covariant to setters with polymorphism.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/polymorphism.dart
end_to_end_test/lib/polymorphism.g.dart
end_to_end_test/lib/polymorphism_nnbd.g.dart

Generation fix

---

CHANGELOG.md
end_to_end_test/lib/generics_nnbd.dart
end_to_end_test/lib/generics_nnbd.g.dart
end_to_end_test/test/generics_nnbd_test.dart

Initialize generics

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_analyzer_plugin/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Release 8.0.4.

---

built_value/lib/json_object.dart
built_value/test/json_object_test.dart

Allow instantiating JsonObject from <dynamic, dynamic>{}.

---

CHANGELOG.md
example/lib/enums.dart

Deprecate angular mixin.

---

built_value_generator/lib/src/serializer_source_class.dart
end_to_end_test/lib/generics_nnbd.dart
end_to_end_test/lib/generics_nnbd.g.dart

Fix generation with empty generic class.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/polymorphism_nnbd.dart
end_to_end_test/lib/polymorphism_nnbd.g.dart
end_to_end_test/test/polymorphism_nnbd_test.dart

Fix nestedBuilders: false with instantiable: false.

---

CHANGELOG.md
built_value_generator/lib/src/serializer_source_library.dart
built_value_generator/lib/src/serializer_source_library.g.dart
built_value_generator/test/serializer_generator_test.dart
example/lib/enums.g.dart

Error on SerializersFor wrong type.

---

CHANGELOG.md
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/polymorphism_nnbd.dart
end_to_end_test/lib/polymorphism_nnbd.g.dart

Support polymorphism with mixed in parent value type.

---

built_value_generator/lib/built_value_generator.dart
built_value_generator/pubspec.yaml

Analyzer 2.0.0 seems to work, tests succeed.
Would be good to get this released.

Add support for analyzer 2.0.0

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_analyzer_plugin/pubspec.yaml
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/pubspec.yaml
built_value_generator/tools/analyzer_plugin/pubspec.yaml
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Remove print.

---

built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/generics_nnbd.dart
end_to_end_test/lib/generics_nnbd.g.dart
end_to_end_test/test/generics_nnbd_test.dart

This fixes the issue caused by #1162.

Fix build() code generation for generic fields

---

CHANGELOG.md
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/test/enum_class_generator_test.dart
end_to_end_test/lib/enums_nnbd.dart
end_to_end_test/lib/enums_nnbd.g.dart

Allow enums to use 2.17 super init feature.

---

built_value_generator/lib/src/value_source_class.dart

refactor(built_value_generator): generate hashCode by using n statements for n fields instead of one nested expression that is nested n levels deep

---

AUTHORS
built_value_generator/lib/src/value_source_class.dart
end_to_end_test/lib/serializers_nnbd.dart
end_to_end_test/lib/serializers_nnbd.g.dart
end_to_end_test/lib/values_nnbd.dart
end_to_end_test/lib/values_nnbd.g.dart
end_to_end_test/test/values_nnbd_serializer_test.dart

fixes #1233
Gonna sign the cla shortly.

escape field name on _$failedField

---

built_value/pubspec.yaml
built_value_analyzer_plugin/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_test/pubspec.yaml

Just drive-by proposal of topics :D

Add topics

---

CHANGELOG.md
built_value_generator/lib/src/enum_source_class.dart
built_value_generator/lib/src/enum_source_class.g.dart
built_value_generator/test/enum_class_generator_test.dart
end_to_end_test/lib/enums_nnbd.dart
end_to_end_test/lib/enums_nnbd.g.dart
end_to_end_test/test/enums_nnbd_test.dart

Fix mixin class generation for Dart 3.

---

CHANGELOG.md
benchmark/pubspec.yaml
built_value/pubspec.yaml
built_value_generator/pubspec.yaml
built_value_generator/test/built_value_generator_test.dart
built_value_generator/test/enum_class_generator_test.dart
built_value_test/pubspec.yaml
chat_example/pubspec.yaml
end_to_end_test/pubspec.yaml
example/pubspec.yaml

Bump analyzer version. Release 8.6.3.

---

built_value/lib/serializer.dart
built_value/lib/src/int32_serializer.dart
built_value/test/int32_serializer_test.dart

feat: add Int32 serializer

---

CHANGELOG.md
built_value/lib/src/built_json_serializers.dart
built_value_generator/lib/src/serializer_source_field.dart
built_value_generator/test/serializer_generator_test.dart
end_to_end_test/lib/records.dart
end_to_end_test/lib/records.g.dart
end_to_end_test/test/records_serializer_test.dart

Allow types with record fields to be serialized via typedef and custom serializer
