google/built_value.dart

- built_value_generator/lib/src/built_parameters_visitor.dart
- built_value_generator/lib/src/source_class.dart
- built_value_generator/test/built_value_generator_test.dart
Don't assume builder can be resolved, it might be generated and so not available yet.
Switch to AST-based check so the builder doesn't need to exist yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/46)
> Fix generic parameter checking.

- CHANGELOG.md
- built_value/lib/built_value.dart
- built_value/pubspec.yaml
- built_value_generator/lib/src/source_class.dart
- built_value_generator/lib/src/source_class.g.dart
- built_value_generator/lib/src/source_field.g.dart
- example/lib/collections.g.dart
- example/lib/compound_value.g.dart
- example/lib/simple_value.g.dart
- example/lib/validated_value.g.dart
- example/lib/value_with_code.g.dart
- example/lib/value_with_defaults.g.dart
- example/pubspec.yaml
- example/test/benchmark_test.dart
- example/test/collections_test.dart
- example/test/compound_value_test.dart
- example/test/simple_value_test.dart
Creating a list to pass to quiver's hash method was a big overhead. Instead, add the internals of quiver hash to built_value.dart and generate equivalent code that doesn't need to instantiate a list.
See https://github.com/google/quiver-dart/blob/master/lib/src/core/hash.dart
For a two field class (SimpleValue):
Performance before: 1.2M hashes/s on Chrome, 24M hashes/s on VM
After: 19M hashes/s on Chrome, 95-101M hashes/s on VM
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/49)
> Add benchmark for hashing. Improve hashing performance.

- .analysis_options
- .travis.yml
- CHANGELOG.md
- README.md
- built_value/lib/built_value.dart
- built_value/pubspec.yaml
- built_value/test/built_value_test.dart
- built_value_generator/lib/built_value_generator.dart
- built_value_generator/lib/src/built_parameters_visitor.dart
- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_class.g.dart
- built_value_generator/lib/src/enum_source_field.dart
- built_value_generator/lib/src/enum_source_field.g.dart
- built_value_generator/lib/src/enum_source_library.dart
- built_value_generator/lib/src/enum_source_library.g.dart
- built_value_generator/lib/src/library_elements.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_class.g.dart
- built_value_generator/lib/src/value_source_field.dart
- built_value_generator/lib/src/value_source_field.g.dart
- built_value_generator/pubspec.yaml
- built_value_generator/test/enum_class_generator_test.dart
- example/lib/test_enum.dart
- example/lib/test_enum.g.dart
- example/pubspec.yaml
- example/tool/watch.dart
- libraries_for_object_oriented_dart.md
From https://github.com/google/enum_class.dart
The files are straight moves/renames, except:
- the main generator class delegates to either enum or value generation as needed
- docs are merged
- imports, filenames, etc, are fixed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/51)
> Merge in enum_class and enum_class_generator.

- CHANGELOG.md
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/test/built_value_generator_test.dart
Fixes #71
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/77)
> Allow "updates" in value type factory to have explicit void return type.

- benchmark/lib/node.g.dart
- benchmark/lib/simple_value.g.dart
- benchmark/pubspec.yaml
- built_value_generator/lib/src/enum_source_class.g.dart
- built_value_generator/lib/src/enum_source_field.g.dart
- built_value_generator/lib/src/enum_source_library.g.dart
- built_value_generator/lib/src/serializer_source_class.g.dart
- built_value_generator/lib/src/serializer_source_field.g.dart
- built_value_generator/lib/src/serializer_source_library.g.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_class.g.dart
- built_value_generator/lib/src/value_source_field.g.dart
- built_value_generator/pubspec.yaml
- chat_example/lib/data_model/data_model.g.dart
- chat_example/pubspec.yaml
- example/lib/collections.g.dart
- example/lib/compound_value.g.dart
- example/lib/has_int.g.dart
- example/lib/simple_value.g.dart
- example/lib/validated_value.g.dart
- example/lib/value_with_code.g.dart
- example/lib/value_with_defaults.g.dart
- example/pubspec.yaml
- example/test/simple_value_test.dart
- example/test/value_with_defaults_test.dart
Renamed "_$writableBuilder" to "_$this", since
- it's now used for all the setters and getters in the builder, not just setters (which is why it was "writable")
- a longer name didn't seem to add much, and we might as well keep the generated code a bit shorter
Fixes #80 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/81)
> Fix builder getters to be available before set.

- benchmark/pubspec.yaml
- built_value/pubspec.yaml
- built_value_generator/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/lib/generics.g.dart
- end_to_end_test/pubspec.yaml
- example/lib/generics.g.dart
- example/pubspec.yaml
+ Add null check to generated builder "replace" methods.
+ Fail with error on abstract enum classes.
+ Update to build 0.7.0, build_runner 0.3.0, and build_test 0.4.0.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/115)
> Better checking, update deps

- benchmark/pubspec.yaml
- built_value/pubspec.yaml
- built_value_generator/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/pubspec.yaml
- example/pubspec.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/141)
> Release 0.5.5.

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value_generator/lib/built_value_generator.dart
- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_class.g.dart
- built_value_generator/lib/src/enum_source_field.dart
- built_value_generator/lib/src/enum_source_field.g.dart
- built_value_generator/lib/src/enum_source_library.dart
- built_value_generator/lib/src/enum_source_library.g.dart
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/lib/src/serializer_source_class.g.dart
- built_value_generator/lib/src/serializer_source_field.dart
- built_value_generator/lib/src/serializer_source_field.g.dart
- built_value_generator/lib/src/serializer_source_library.dart
- built_value_generator/lib/src/serializer_source_library.g.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_class.g.dart
- built_value_generator/lib/src/value_source_field.dart
- built_value_generator/lib/src/value_source_field.g.dart
- built_value_generator/pubspec.yaml
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/pubspec.yaml
- example/pubspec.yaml
Straightforward refactor with no change to functionality or tests: instead of precomputing everything in e.g. ValueSourceClass constructor, store analyzer elements and do computation on them only in @memoized getters.
Significantly faster at build time when there is irrelevant code visible to the analyzer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/168)
> Significantly improve build performance by using @memoized instead of precomputed fields.

- CHANGELOG.md
- built_value_generator/lib/src/memoized_getter.dart
- built_value_generator/lib/src/metadata.dart
- built_value_generator/lib/src/serializer_source_field.dart
- built_value_generator/lib/src/value_source_field.dart
Fixes #220 
For real this time :)
The problem was that the "constantValue" getter is allowed to sometimes return null. What I really wanted was "computeConstantValue". This PR also improves handling if there is a missing import.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/222)
> Improve annotation handling.

- CHANGELOG.md
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_class.g.dart
- example/lib/polymorphism.dart
- example/lib/polymorphism.g.dart
Fixes #232
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/233)
> Add workaround for dart2js issue with polymorphism.

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value/lib/src/built_list_multimap_serializer.dart
- built_value/lib/src/built_list_serializer.dart
- built_value/lib/src/built_map_serializer.dart
- built_value/lib/src/built_set_serializer.dart
- built_value/pubspec.yaml
- built_value/test/built_list_multimap_serializer_test.dart
- built_value/test/built_list_serializer_test.dart
- built_value/test/built_map_serializer_test.dart
- built_value/test/built_set_multimap_serializer_test.dart
- built_value/test/built_set_serializer_test.dart
- built_value_generator/pubspec.yaml
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/pubspec.yaml
- example/pubspec.yaml
- Get the actual `runtimeType` of collections for serialization, instead of assuming we know it.
- Stop using strings for `runtimeType` in tests and use actual values.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/264)
> Fix for built_collection 2.0.

- README.md
I've added a live template for generating bits of boilerplate required to use built_value and decided to share it in the docs. Not sure whether README.md is the best place for that but there doesn't seem to be other places to put docs to?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/268)
> Add a recipe for boilerplate generation in IntelliJ

- AUTHORS
- built_value/lib/built_value.dart
- built_value_generator/lib/src/metadata.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_field.dart
- built_value_generator/lib/src/value_source_field.g.dart
- built_value_test/test/matcher_test.dart
- built_value_test/test/values.dart
- built_value_test/test/values.g.dart
- end_to_end_test/test/to_string_test.dart
- end_to_end_test/test/values_test.dart
I've had an issue with using flutter_redux and when creating a ViewModel for the store to pass on to the widget, I wasn't able to compare the old ViewModel instance with the new one every time a change happened. Since I had to pass a `String code` and a `Function onChange` (for dispatching actions) field in the ViewModel.
And when the field `code` is being compared it will return `true` however because the `onChange` field is a closure function, it always compares as `false` so the widget gets updated even when there is no direct change for this widget in the state.
```
(store) => new RoomTypeDropdownViewModel((b) => b
..code = store.state.roomTypeCode
..onChanged = (v) => store.dispatch({
'type': SearchRoomTypeActions.Select,
'room_type': v
}));
```
I think we need a way to make `bool …
> Add ignored annotation for fields that should not be compared

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value_generator/lib/src/value_source_field.dart
- built_value_generator/pubspec.yaml
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/lib/values.dart
- end_to_end_test/lib/values.g.dart
- end_to_end_test/pubspec.yaml
- example/pubspec.yaml
Fixes #281 
We were getting the field names via a different codepath for builders, and this didn't work for functions; use the same codepath.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/284)
> Fix function types in generated builders.

- CHANGELOG.md
- built_value/lib/async_serializer.dart
- built_value/test/built_list_async_deserializer_test.dart
Fixes #105 
This seems a much simper approach than the ones discussed on that issue; we just provide support for asynchronously deserializing a top level list.
This approach could be expanded to asynchronously deserializing other types--but you will in general only need to do this for the top level type in the payload, to split the work into chunks. This PR ought to be enough to show the concept works.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/297)
> Add BuiltListAsyncDeserializer.

- .gitignore
The .dart_tool directory is the new canonical location for cache/temp
files for Dart-related tooling.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/370)
> Add .dart_tool to gitignore

- README.md
There is an extra dollar sign on the boilerplate template.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/423)
> Remove extra dollar sign

- built_value_generator/pubspec.yaml
Without this change, `_PUB_TEST_SDK_VERSION=2.0.0 pub upgrade` won't complete successfully.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/466)
> Upgrade to Dart2-compatible analyzer_plugin

- built_value_generator/pubspec.yaml
Previously built_value_generator relied on build ^0.0.12, and the build package is 1.0. I don't see any reason why I shouldn't allow 1.0, so I upped the version constraint.
Modify pubspec to allow build package of 1.0 and greater (up to next potentially breaking change of 2.0)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/511)
> Modify pubspec to allow build package of 1.0 and greater

- built_value_generator/lib/built_value_generator.dart
The generated files created seems to not include `always_specify_types` among the generated ignored linters. This causes problems with the default flutter `analysis_options.yaml` and results in a pretty unreadable analyzer output.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/google/built_value.dart/584)
> Add ignored linter conflicting with flutter defaults

- CHANGELOG.md
- built_value_generator/lib/src/value_source_class.dart
- end_to_end_test/lib/values.dart
- end_to_end_test/lib/values.g.dart
- end_to_end_test/test/values_test.dart
> Allow providing your own `toString` via a mixin.

- CHANGELOG.md
- built_value_generator/lib/src/serializer_source_class.dart
- end_to_end_test/lib/collections.dart
- end_to_end_test/lib/collections.g.dart
- end_to_end_test/lib/serializers.dart
- end_to_end_test/lib/serializers.g.dart
- end_to_end_test/lib/standard_json.g.dart
- end_to_end_test/lib/values.g.dart
- end_to_end_test/test/collections_serializer_test.dart
- example/lib/collections.g.dart
- example/lib/values.g.dart
Fixes #641 
When generating a serializer with `serializeNulls: true`, do all null handling in the generated code. This avoids problems with trying to get a null value to pass through all the standard serialize logic, just for the sake of getting a null out again.
> Fix `BuiltValueSerializer(serializeNulls: true)` for non-primitive fields.

- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_library.dart
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/lib/src/serializer_source_library.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/pubspec.yaml
This was a temporary analyzer API; it has been deprecated and replaced
by a method in AnalysisSession.
> Stop making use of the `tmp` constructor for `ParsedLibraryResultImpl`.

- README.md
README.md was using plain code blocks, which resulted in no syntax highlighting, making those snippets harder to read.
This PR adds languages to the blocks to enable highlighting.
> Enable syntax highlighting in README code blocks

- CHANGELOG.md
- built_value_generator/pubspec.yaml
We change `DartEditBuilder.writeOverride` in https://dart-review.googlesource.com/c/sdk/+/110941, as far as I can see, this does not affect your plugin. So, you can set your version range for "analyzer_plugin" higher.
> Change analyzer_plugin version range.

- built_value/lib/serializer.dart
The issue I'm fixing here is the second parameter passed to `addBuilderFactory` should be `() => ListBuilder<Foo>()` but currently it's missing the `()` after `<Foo>`. I also updated the syntax to remove the `new` keyword and formatted the code with dartfmt.
> serializers: fix syntax in addBuilderFactory dartdoc

- CHANGELOG.md
- built_value_generator/lib/src/dart_types.dart
- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_field.dart
- built_value_generator/lib/src/memoized_getter.dart
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/lib/src/serializer_source_field.dart
- built_value_generator/lib/src/serializer_source_library.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_field.dart
Stop using DartType.toString() for code generation.
We would like to change DartType.toString() to include nullability suffixes `?` and `*`. And it actually has never been a really good idea to use `toString()` or `DartType.displayName` for code generation.
> Use DartTypes.getName() instead of DartType.displayName

- CHANGELOG.md
- built_value/lib/src/num_serializer.dart
> Fix `num` deserialization so it does not always convert to `double`.

- example/lib/values.dart
`@virtual` is no longer needed and the field isn't annotated with it anyway.
> Remove the comment about @virtual

- built_value_generator/lib/src/serializer_source_class.dart
We did this some time ago, but because it is not enforced, probably another one crept in.
> Use DartTypes.getName() instead of DartType.toString()

- built_value/lib/async_serializer.dart
Since this package does not support Dart 2.0, this import is not
necessary.
> Remove unused dart:async import

- built_value/lib/standard_json_plugin.dart
Otherwise json deserialization using standard_json_plugin fails in null safe mode
> Convert List<dynamic> to List<Object> in standard_json_plugin

- built_value_generator/test/built_value_generator_test.dart
- built_value_generator/test/enum_class_generator_test.dart
- built_value_generator/test/serializer_generator_test.dart
I was thinking about how to contribute one feature and got lost in the tests, so I'm opening this to see if it makes sense to you., I believe that grouping the tests make them more clear and may guide other people to contribute.
If you check the `flutter outline` window on IntelliJ the changes look like this:
WDYT?
> Add groups to tests

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value/pubspec.yaml
- built_value_analyzer_plugin/pubspec.yaml
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/pubspec.yaml
- built_value_generator/test/serializer_generator_test.dart
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/analysis_options.yaml
- end_to_end_test/lib/collections_nnbd.g.dart
- end_to_end_test/lib/generics_nnbd.g.dart
- end_to_end_test/lib/imported_values_nnbd.g.dart
- end_to_end_test/lib/interfaces_nnbd.g.dart
- end_to_end_test/lib/polymorphism_nnbd.g.dart
- end_to_end_test/lib/standard_json_nnbd.g.dart
- end_to_end_test/lib/values_nnbd.g.dart
- end_to_end_test/pubspec.yaml
- end_to_end_test/test/values_nnbd_test.dart
- example/pubspec.yaml
- tool/presubmit
Fixes #1101.
The change adds a couple' null asserts to `deserialize` to prevent cast_nullable_to_non_nullable lint warning.
> Make generated deserialize method not throw cast_nullable_to_non_nullable lint warning

- CHANGELOG.md
- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/test/enum_class_generator_test.dart
- end_to_end_test/lib/enums.dart
Solves #1093.
This change allows using final params in a class inheriting from `EnumClass`, for its constructor, and `valueOf` method.
I also had to replace the usages of `interfaces2` with `interfaces` (due to deprecation) in [value_source_class.dart](https://github.com/google/built_value.dart/blob/master/built_value_generator/lib/src/value_source_class.dart) for tool/presubmit to pass.
> Support final parameters in EnumClass constructor and valueOf method.

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value/pubspec.yaml
- built_value_analyzer_plugin/pubspec.yaml
- built_value_generator/pubspec.yaml
- built_value_generator/tools/analyzer_plugin/pubspec.yaml
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/pubspec.yaml
- example/pubspec.yaml
Fix deps range for `built_value_generator`.
> Release 8.2.1.

- AUTHORS
- CHANGELOG.md
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_field.dart
- end_to_end_test/lib/generics_nnbd.dart
- end_to_end_test/lib/generics_nnbd.g.dart
- end_to_end_test/test/generics_nnbd_test.dart
Currently, the library doesn't support optional generic bounds. The optionality of the bounds is simply dropped, resulting in a built value that behaves differently than its abstract class.
The following code
```dart
abstract class Box<T extends Content?> implements Built<Box<T>, BoxBuilder<T>> {
...
}
```
results in the generation of
```dart
class _$Box<T extends Content> extends BoxValue<T> {
...
}
class BoxBuilder<T extends Content> implements Builder<Box<T>, BoxBuilder<T>> {
....
}
```
The correct behavior would be the retention of the question mark (`T extends Content?`). This pull request resolves this issue.
> Implement support for optional generic bounds

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value/pubspec.yaml
- built_value_analyzer_plugin/pubspec.yaml
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_field.dart
- built_value_generator/lib/src/value_source_field.g.dart
- built_value_generator/pubspec.yaml
- built_value_generator/test/built_value_generator_test.dart
- built_value_generator/tools/analyzer_plugin/pubspec.yaml
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/lib/values.g.dart
- end_to_end_test/lib/values_nnbd.dart
- end_to_end_test/lib/values_nnbd.g.dart
- end_to_end_test/pubspec.yaml
- end_to_end_test/test/values_nnbd_test.dart
- example/pubspec.yaml
Fixes #1173.
Previously, getters and setters could only be explicitly defined. This made sense for pre-null-safety, since there wasn't any reason to create a getter/setter pair over a normal field. However, with null safety, there was no way to use custom builders that had nested builders.
This fixes the bug where nested builders couldn't be used in custom builders, as well as allows the definition of abstract getters and setters such that auto created nested builders can also be utilized without needing null checks (by defining a setter with a nullable parameter).
> Fix nested builder bug in custom builders, and allow define abstract getters/setters in custom builders

- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_class.g.dart
- built_value_generator/lib/src/enum_source_field.dart
- built_value_generator/lib/src/fields.dart
- built_value_generator/lib/src/memoized_getter.dart
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/lib/src/serializer_source_class.g.dart
- built_value_generator/lib/src/serializer_source_library.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_class.g.dart
- built_value_generator/lib/src/value_source_field.dart
All three implement InterfaceElement, but in the breaking change for analyzer we will stop implementing ClassElement in EnumElement and MixinElement. This is a minimal change necessary to make google3 green, the might be need for more changes that are not exercised there.
> Prepare for separating ClassElement, EnumElement, and MixinElement.

- .github/dependabot.yaml
- .github/workflows/build.yaml
- .travis.yml
- README.md
- add github actions support
- add a CI status badge to the readme
- configure dependabot in order to keep the github action versions up-to-date
- remove the older travis configuration file
cc @davidmorgan
> add github actions support

- CHANGELOG.md
- built_value_generator/lib/src/dart_types.dart
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/lib/src/serializer_source_library.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/pubspec.yaml
> Bump analyzer version, stop using deprecated methods. Release 8.4.2.

- built_value/test/uri_serializer_test.dart
> Simplify URI in test so it parses as a _SimpleUri.

- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_library.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/pubspec.yaml
The package had been used for only two utilities, `concat` and `zip`.
Replace `zip` with `IterableZip` from `package:collection` which is also
an existing dependency.
Replace `concat` with either `...` elements in a list literal (since
the collections are always iterated anyway) or by replacing `.map` with
`.expand`.
> Drop dependency on quiver

- built_value_generator/pubspec.yaml
[The `.element` interface was introduced (and `.element2` was deprecated)][1] in the analyzer at version 5.2.0.
Since, migrating over to the `.element` interface at 05da0d3d78, versions [less than 5.2.0 of the analyzer][2] will not work. 
Here, we update the analyzer dependency accordingly.
Resolves, #1203
[1]: https://github.com/dart-lang/sdk/commit/683e2419da03b68074c9c744d9c2566f51c588f5
[2]: https://github.com/google/built_value.dart/blob/v8.4.3/built_value_generator/pubspec.yaml#L12
> upgrade analyzer dependency to 5.2.0

- built_value/lib/serializer.dart
- built_value/lib/src/uint8list_serializer.dart
- built_value/test/uint8list_serializer_test.dart
Support Uint8List by converting to and from base64 encoded strings. 
[Older Feature Request](https://github.com/google/built_value.dart/issues/194)
> Adds Uint8List serializer

- CHANGELOG.md
- built_value_generator/lib/src/dart_types.dart
- end_to_end_test/lib/mixins_src.dart
- end_to_end_test/lib/values.dart
- end_to_end_test/lib/values.g.dart
> Support optional and named args in Function types.

- built_value_generator/lib/src/serializer_source_class.dart
- end_to_end_test/lib/enums.dart
- end_to_end_test/lib/enums.g.dart
Wire keys of enums need to be escaped in order to properly generate fields that start with a `$` (otherwise interpreted as variables). For example these were not possible before:
```dart
class Base_EnumInt extends EnumClass {
const Base_EnumInt._(super.name);
@BuiltValueEnumConst(wireName: '0')
static const Base_EnumInt $0 = _$baseEnumInt$0;
@BuiltValueEnumConst(wireName: '1')
static const Base_EnumInt $1 = _$baseEnumInt$1;
@BuiltValueEnumConst(wireName: '2')
static const Base_EnumInt $2 = _$baseEnumInt$2;
static BuiltSet<Base_EnumInt> get values => _$baseEnumIntValues;
static Base_EnumInt valueOf(final String name) => _$valueOfBase_EnumInt(name);
static Serializer<Base_EnumInt> get serializer => _$baseEnumIntSerializer;
}
class Base_EnumString extends EnumClass {
const …
```
> fix(build_value_generator): Escape enum wire keys

- CHANGELOG.md
- built_value_generator/lib/src/enum_source_class.dart
- end_to_end_test/lib/enums.dart
- end_to_end_test/lib/enums.g.dart
> feat: allow non alphanumeric characters in enum class names

- built_value_generator/lib/src/dart_types.dart
- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/fields.dart
- built_value_generator/lib/src/serializer_source_library.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/pubspec.yaml
Preparation for https://dart-review.googlesource.com/c/sdk/+/385100
> Require 'analyzer 6.9.0+' and SDK 3.6.0-edge

- built_value/lib/built_value.dart
Legacy Dart is already unsupported and the annotation already causes an error whenever built_value can detect it, *but* it's possible to put this annotation into a completely unrelated place and it will just stay there doing nothing. So the least we can do is to deprecate this annotation.
> Deprecate `@nullable` annotation

- README.md
- end_to_end_test/test/mixins_test.dart
> Remove use of deprecated @nullable from docs and comments.

- CHANGELOG.md
- benchmark/pubspec.yaml
- built_value_generator/lib/built_value_generator.dart
- built_value_generator/lib/src/enum_source_class.dart
- built_value_generator/lib/src/enum_source_field.dart
- built_value_generator/lib/src/field_mixin.dart
- built_value_generator/lib/src/serializer_source_class.dart
- built_value_generator/lib/src/serializer_source_field.dart
- built_value_generator/lib/src/value_source_class.dart
- built_value_generator/lib/src/value_source_field.dart
- built_value_generator/pubspec.yaml
- built_value_test/pubspec.yaml
- chat_example/pubspec.yaml
- end_to_end_test/pubspec.yaml
- example/pubspec.yaml
`library.element2` -> `library.element`
Incidental changes: stop using method that's now deprecated in the analyzer, change dep pinning to something that currently builds.
> Use renamed `source_gen` method.

- README.md
I updated the Flutter codegen command in the README from the deprecated `flutter packages pub run build_runner build` to `dart run build_runner build`.
> Update codegen documentation in README
